name: format_and_commit

on:
  pull_request:
    type: [closed]
jobs:
  formatter:
    runs-on: windows-latest
    steps:
      - name: Checktest
        uses: actions/checkout@v3

      - name: Auto-commit if changes
        run: |

          git add .
          git commit -m "Apply Code Formatter Change" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
          
          